controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\DishOrder;
use app\models\GlobalModel;
use app\models\User;
use Yii;
use yii\base\InvalidCallException;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;

/**
 * SiteController controller class.
 *
 * @author Antanas Šiaulys <antanas.siaulys@ktu.edu>
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'user-login', 'user-register', 'user-validation'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => [
                            'error', 'index',
                            'user-admin-register', 'user-logout', 'user-list', 'user-view', 'change-user', 'user-remove', 'user-validation',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $months = '';
        $ordersAmount = '';
        $specificUserApproved = '';

        for ($i = date('n') + 1; $i <= 12; $i++) {
            $time[0] = gmmktime(0, 0, 0, $i, 1, date('Y') - 1);
            $time[1] = gmmktime(23, 59, 59, $i, cal_days_in_month(CAL_GREGORIAN, $i, date('Y')), date('Y') - 1);
            $ordersAmount .= count(DishOrder::getOrdersBetweenMonth($time[0], $time[1])).', ';
            $specificUserApproved .= count(DishOrder::getOrdersBetweenMonth(
                    $time[0], $time[1], 'approver_id = '.Yii::$app->user->id
                )).', ';
            $months .= '"'.GlobalModel::getAllMonths($i).'", ';
        }

        for ($i = date('n'); $i > 0; $i--) {
            $time[0] = gmmktime(0, 0, 0, $i, 1, date('Y'));
            $time[1] = gmmktime(23, 59, 59, $i, cal_days_in_month(CAL_GREGORIAN, $i, date('Y')), date('Y'));
//          $ordersAmount[$j] = count(DishOrder::getOrdersBetweenMonth($time[0], $time[1])); // Fits if array
            $ordersAmount .= count(DishOrder::getOrdersBetweenMonth($time[0], $time[1])).', ';
            $specificUserApproved .= count(DishOrder::getOrdersBetweenMonth(
                    $time[0], $time[1], 'approver_id = '.Yii::$app->user->id
                )).', ';
            $months .= '"'.GlobalModel::getAllMonths($i).'", ';
        }

        $months = substr($months, 0, -2);
        $ordersAmount = substr($ordersAmount, 0, -2);
        $specificUserApproved = substr($specificUserApproved, 0, -2);

        return $this->render('index', [
            'list' => $months,
            'ordersAmount' => $ordersAmount,
            'specificUserApproved' => $specificUserApproved,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionUserLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $post = Yii::$app->request->post();
        $model = new User();
        $model->scenario = User::SCENARIO_LOGIN;

        if ($model->load($post) && $model->login()) {
            Yii::$app->session->setFlash('success', 'Sėkmingai prisijungėte prie sąskaitos.');

            return $this->redirect(['index']);
        } elseif (Yii::$app->request->isPost) {
            Yii::$app->session->setFlash('error', 'Prisijungimas nepavyko. Blogi prisijungimo duomenys.');

            return $this->redirect(['index']);
        }

        return $this->render('user-login', [
            'model' => $model,
        ]);
    }

    /**
     * Register action.
     *
     * @return string
     */
    public function actionUserRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $post = Yii::$app->request->post();
        $model = new User();
        $model->scenario = User::SCENARIO_CREATE;

        if (!empty($post)) {
            if ($model->createNewUser($post)) {
                Yii::$app->session->setFlash('success', 'Vartotojo sąskaita sėkmingai sukurta.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Vartotojo sąskaitos sukurti nepavyko. Pabandykite dar kartą.');
            }
        }

        return $this->render('user-register', [
            'model' => $model,
        ]);
    }

    /**
     * Register action for first user.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionUserAdminRegister()
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $post = Yii::$app->request->post();
        $model = new User();
        $model->scenario = User::SCENARIO_CREATE;

        if (!empty($post)) {
            if ($model->createNewUser($post)) {
                Yii::$app->session->setFlash('success', 'Vartotojo sąskaita sėkmingai sukurta.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Vartotojo sąskaitos sukurti nepavyko. Pabandykite dar kartą.');
            }
        }

        return $this->render('user-admin-register', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionUserLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays all users.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionUserList()
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $user = new User();
        $user->scenario = User::SCENARIO_SEARCH;
        $userProvider = $user->search(Yii::$app->request->get());

        return $this->render('user-list', [
            'model' => $user,
            'modelProvider' => $userProvider,
        ]);
    }

    /**
     * Renders profile viewing.
     *
     * @param integer $id User's ID.
     * @return string
     * @throws HttpException
     */
    public function actionUserView($id = null)
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (empty($id)) {
            throw new ForbiddenHttpException('Trūksta parametrų.');
        }

        if ($id == 1 && Yii::$app->user->id != $id) {
            throw new ForbiddenHttpException('Pagrindinio administratoriaus sąskaita negali būti peržiūrėta arba koreguota.');
        }

        $model = (new User())->findOne(['id' => $id]);

        if (is_null($model)) {
            throw new NotFoundHttpException('Vartotojas nerastas.');
        }

        return $this->render('user-view', [
            'model' => $model,
        ]);
    }

    /**
     * Changes information about User.
     *
     * @param integer $id User ID.
     * @return string json_encode Results.
     * @throws HttpException User not found.
     */
    public function actionChangeUser($id = null)
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $post = Yii::$app->request->post();

        if (empty($post)) {
            throw new ForbiddenHttpException('Tiesioginis priėjimas draudžiamas.');
        }

        $attribute = key($post['User']);

        if (!in_array($attribute, ['username', 'real_name', 'password', 'email', 'type'])) {
            return json_encode(['output' => '', 'message' => 'Redaguojamas atributas nepriimamas.']);
        } elseif (Yii::$app->user->identity->type < 3) {
            return json_encode(['output' => '', 'message' => 'Tik administratorius gali vykdyti šiuos veiksmus.']);
        } elseif ($id == 1) {
            return json_encode(['output' => '', 'message' => 'Pagr. administratoriaus duomenų keisti negalima.']);
        }

        $model = (new User())->findOne($id);

        if (is_null($model)) {
            return json_encode(['output' => '', 'message' => 'Vartotojas nerastas.']);
        }

        $model->scenario = User::SCENARIO_EDIT;
        $model->$attribute = $post['User'][$attribute];

        if ($attribute == 'type') {
            if (!in_array($post['User']['type'], [1, 2, 3])) {
                return json_encode(['output' => '', 'message' => 'Netinkamas tipas.']);
            }

            $post['User'][$attribute] = User::getTypeName()[$post['User']['type']];
        }

        if ($model->save())
            return json_encode(['output' => Html::encode($post['User'][$attribute]), 'message' => '']);
        else
            return json_encode(['output' => '', 'message' => $model->firstErrors[$attribute]]);
    }

    /**
     * Removes existing user.
     *
     * @param integer $id User's ID.
     * @return string
     * @throws HttpException
     */
    public function actionUserRemove($id = null)
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (empty($id)) {
            throw new ForbiddenHttpException('Trūksta parametrų.');
        }

        if ($id == 1) {

views/layouts/_menu_login.php
<?php

use app\models\User;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$model = new User();
$model->scenario = User::SCENARIO_LOGIN;

Modal::begin([
    'id' => 'login_modal',
    'header' => Html::tag('h4', 'Vartotojo prisijungimas', ['class' => 'modal-title']),
    'footer' => '',
    'size' => Modal::SIZE_LARGE,
]);

$form = ActiveForm::begin([
    'id' => 'login-form',
    'action' => Url::to(['site/user-login']),
]);

echo $form->field($model, 'username', ['options' => ['class' => 'form-group col-xs-6']])->textInput(['class' => 'form-control']);
echo $form->field($model, 'password', ['options' => ['class' => 'form-group col-xs-6']])->passwordInput();
?>

<div class="col-xs-12">
    <p>Norėdami prisijungti, įveskite vartotojo vardą, slaptažodį ir paspauskite „prisijungti".</p>
    <div class="text-center">
        <?= Html::submitButton('Prisijungti', ['class' => 'btn btn-info', 'name' => 'login-button']) ?>
    </div>
</div>

<?php
ActiveForm::end();
Modal::end();

views/layouts/_menu_register.php
<?php

use app\models\User;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$model = new User();
$model->scenario = User::SCENARIO_CREATE;

Modal::begin([
    'id' => 'register_modal',
    'header' => Html::tag('h4', 'Vartotojo registracija', ['class' => 'modal-title']),
    'footer' => '',
    'size' => Modal::SIZE_LARGE,
 ]);

$form = ActiveForm::begin([
    'id' => 'register-form',
    'action' => Url::to(['site/user-register']),
    'enableAjaxValidation' => true,
    'validationUrl' => Url::to(['site/user-validation']),
]);

echo $form->field($model, 'username', ['options' => ['class' => 'form-group col-xs-6']])->textInput(['class' => 'form-control']);
echo $form->field($model, 'password', ['options' => ['class' => 'form-group col-xs-6']])->passwordInput();
echo $form->field($model, 'email', ['options' => ['class' => 'form-group col-xs-6']])->textInput(['class' => 'form-control']);
echo $form->field($model, 'real_name', ['options' => ['class' => 'form-group col-xs-6']])->textInput(['class' => 'form-control']);
?>

    <div class="col-xs-12">
        <p>Registracijai reikalingi: vartotojas vardas, slaptažodis, el. paštas ir tikrasis vardas.
            Tik tikrasis vardas yra matomas kitiems vartotojams.</p>
        <p>Visi laukai yra privalomi.</p>
        <div class="text-center">
            <?= Html::submitButton('Registruotis', ['class' => 'btn btn-info', 'name' => 'login-button']) ?>
            <?= Html::tag('p', Html::a('Eiti į registracijos puslapį', Url::to(['site/user-register']))) ?>
        </div>
    </div>

<?php
ActiveForm::end();
Modal::end();

views/layouts/_modal.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

Modal::begin([
    'id' => 'confirm_modal',
    'header' => Html::tag('h3', 'Reikalingas patvirtinimas', ['class' => 'modal-title']),
    'footer' => '',
    'size' => Modal::SIZE_LARGE,
]);
?>

<div class="col-xs-12">
    <p style="text-align: center">Patvirtinkite savo veiksmą, paspausdami mygtuką „patvirtinti".</p>
    <div class="text-center">
        <?= Html::a(Html::button('Patvirtinti', ['class' => 'btn btn-info']), null, ['id' => 'confirm_modal_button']) ?>
    </div>
</div>

<?php
Modal::end();

views/layouts/main.php
<?php

use app\models\Category;
use app\models\User;
use rmrevin\yii\fontawesome\FA;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/** @var View $this */
/** @var $content string */
/** @var array $categoryList */

AppAsset::register($this);
$this->beginPage();
date_default_timezone_set('Europe/Vilnius');

$categories = Category::getRootCategories();

for ($i = 0; $i < count($categories); $i++) {
    $categoryList[$i] = [
        'label' => FA::icon('coffee').' '.$categories[$i]['name'].' ('.count($categories[$i]['dishes']).')',
        'url' => Url::to(['/meal/meal-index', 'Meal[category]' => $categories[$i]['id']])
    ];
}

?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?> :: <?= Yii::$app->params['siteTitle'] ?></title>
    <link rel="shortcut icon" href="../web/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../web/images/favicon.ico" type="image/x-icon">
    <?php $this->head() ?>
</head>
<body>
<?php
$this->beginBody();
NavBar::begin();
NavBar::end();

$user = User::getUserDetails(Yii::$app->user->id);
?>

<div id="main_site_page" class="wrap">
    <div id="main_header_menu">
        <?php if (!Yii::$app->user->isGuest): ?>
            <div id="main_header_div"><button class="btn main_header_button">Prisijungęs vartotojas:<br><?php echo $user['real_name'].' ('.$user['email'].')' ?></button></div>
        <?php endif; ?>
    </div>
    <div id="main_side_menu" class="nav-side-menu">
        <div class="menu-list">
            <a href="<?php echo Url::to(['/site/index']) ?>"><img src="../web/images/logo-2958.png" class="brand" alt="Logo"></a>
            <?php
            echo '<div id="menu_ul">';
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav'],
                'encodeLabels' => false,
                'items' => [
                    Html::tag('span', '<br>Pagrindiniai veiksmai', ['class' => 'menu_title']),
                    [
                        'label' => FA::icon('home').'Namai',
                        'url' => ['/site/index'],
                        'options' => [
                            'class' => (Yii::$app->controller->action->id == 'index' ? 'highlighted' : ''),
                        ],
                    ],
                    [
                        'label' => FA::icon('cutlery').'Patiekalai',
                        'url' => ['/meal/meal-index'],
                        'visible' => !Yii::$app->user->isGuest,
                        'options' => [
                            'class' => (Yii::$app->controller->action->id == 'meal-index' ? 'highlighted' : ''),
                        ],
                    ],
                    (!Yii::$app->user->isGuest && Yii::$app->user->identity->type > 1 ?
                        Html::tag('span', '<br>Administravimas', ['class' => 'menu_title']) :
                    ''),
                    [
                        'label' => FA::icon('book').'Meniu',
                        'url' => ['/meal/menu-index'],
                        'visible' => !Yii::$app->user->isGuest && Yii::$app->user->identity->type > 1,
                        'options' => [
                            'class' => (Yii::$app->controller->action->id == 'menu-index' ? 'highlighted' : ''),
                        ],
                    ],
                    [
                        'label' => FA::icon('credit-card').'Užsakymai',
                        'url' => ['/meal/order-index', 'DishOrder[status]' => 1],
                        'visible' => !Yii::$app->user->isGuest && Yii::$app->user->identity->type > 1,
                        'options' => [
                            'class' => (Yii::$app->controller->action->id == 'order-index' ? 'highlighted' : ''),
                        ],
                    ],
                    [
                        'label' => FA::icon('user-circle').'Vartotojai',
                        'url' => ['/site/user-list'],
                        'visible' => !Yii::$app->user->isGuest && Yii::$app->user->identity->type == 3,
                        'options' => [
                            'class' => (Yii::$app->controller->action->id == 'user-list' ? 'highlighted' : ''),
                        ],
                    ],
                    Html::tag('span', '<br>Vartotojo veiksmai', ['class' => 'menu_title']),
                    [
                        'label' => FA::icon('sign-in').'Prisijungimas',
                        'url' => '#',
                        'visible' => Yii::$app->user->isGuest,
                        'options' => [
                            'id' => 'menu_login',
                        ],
                    ],
                    [
                        'label' => FA::icon('user-plus').'Registracija',
                        'url' => '#',
                        'visible' => Yii::$app->user->isGuest,
                        'options' => [
                            'id' => 'menu_register',
                        ],
                    ],
                    [
                        'label' => FA::icon('sign-out').'Atsijungti',
                        'url' => ['/site/user-logout'],
                        'visible' => !Yii::$app->user->isGuest,
                        'options' => [
                        ],
                    ],
                ],
            ]);
            echo '</div>';

            echo Html::tag('p', '&copy; '.Yii::$app->params['siteTitle'], ['class' => 'footer']);
            echo Html::tag('p', 'Serverio laikas: '.date('Y-m-d H:i'), ['class' => 'footer_clock']);
            ?>
        </div>
    </div>

    <div id="main_menu" class="container">
        <?php if (Yii::$app->session->hasFlash('success')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <span class="glyphicon glyphicon-ok-sign"></span>
                <?php echo Yii::$app->session->getFlash('success'); ?>
            </div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('error')): ?>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign"></span>
                <?php echo Yii::$app->session->getFlash('error'); ?>
            </div>
        <?php endif; ?>

        <?= Breadcrumbs::widget([
            'homeLink' => [
                'label' => 'Pagrindinis',
                'url' => Yii::$app->getHomeUrl() . 'index.php',
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

        <?= $content ?>
    </div>
</div>

<?php
echo $this->render('_modal');

if (Yii::$app->user->isGuest) {
    echo $this->render('_menu_login');
    echo $this->render('_menu_register');
}

$this->endBody();
?>
</body>
</html>
<?php $this->endPage() ?>