controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\DishOrder;
use app\models\GlobalModel;
use app\models\User;
use Yii;
use yii\base\InvalidCallException;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;

/**
 * SiteController controller class.
 *
 * @author Antanas Šiaulys <antanas.siaulys@ktu.edu>
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error', 'user-login', 'user-register', 'user-validation'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => [
                            'error', 'index',
                            'user-admin-register', 'user-logout', 'user-list', 'user-view', 'change-user', 'user-remove', 'user-validation',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $months = '';
        $ordersAmount = '';
        $specificUserApproved = '';

        for ($i = date('n') + 1; $i <= 12; $i++) {
            $time[0] = gmmktime(0, 0, 0, $i, 1, date('Y') - 1);
            $time[1] = gmmktime(23, 59, 59, $i, cal_days_in_month(CAL_GREGORIAN, $i, date('Y')), date('Y') - 1);
            $ordersAmount .= count(DishOrder::getOrdersBetweenMonth($time[0], $time[1])).', ';
            $specificUserApproved .= count(DishOrder::getOrdersBetweenMonth(
                    $time[0], $time[1], 'approver_id = '.Yii::$app->user->id
                )).', ';
            $months .= '"'.GlobalModel::getAllMonths($i).'", ';
        }

        for ($i = date('n'); $i > 0; $i--) {
            $time[0] = gmmktime(0, 0, 0, $i, 1, date('Y'));
            $time[1] = gmmktime(23, 59, 59, $i, cal_days_in_month(CAL_GREGORIAN, $i, date('Y')), date('Y'));
//          $ordersAmount[$j] = count(DishOrder::getOrdersBetweenMonth($time[0], $time[1])); // Fits if array
            $ordersAmount .= count(DishOrder::getOrdersBetweenMonth($time[0], $time[1])).', ';
            $specificUserApproved .= count(DishOrder::getOrdersBetweenMonth(
                    $time[0], $time[1], 'approver_id = '.Yii::$app->user->id
                )).', ';
            $months .= '"'.GlobalModel::getAllMonths($i).'", ';
        }

        $months = substr($months, 0, -2);
        $ordersAmount = substr($ordersAmount, 0, -2);
        $specificUserApproved = substr($specificUserApproved, 0, -2);

        return $this->render('index', [
            'list' => $months,
            'ordersAmount' => $ordersAmount,
            'specificUserApproved' => $specificUserApproved,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionUserLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $post = Yii::$app->request->post();
        $model = new User();
        $model->scenario = User::SCENARIO_LOGIN;

        if ($model->load($post) && $model->login()) {
            Yii::$app->session->setFlash('success', 'Sėkmingai prisijungėte prie sąskaitos.');

            return $this->redirect(['index']);
        } elseif (Yii::$app->request->isPost) {
            Yii::$app->session->setFlash('error', 'Prisijungimas nepavyko. Blogi prisijungimo duomenys.');

            return $this->redirect(['index']);
        }

        return $this->render('user-login', [
            'model' => $model,
        ]);
    }

    /**
     * Register action.
     *
     * @return string
     */
    public function actionUserRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $post = Yii::$app->request->post();
        $model = new User();
        $model->scenario = User::SCENARIO_CREATE;

        if (!empty($post)) {
            if ($model->createNewUser($post)) {
                Yii::$app->session->setFlash('success', 'Vartotojo sąskaita sėkmingai sukurta.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Vartotojo sąskaitos sukurti nepavyko. Pabandykite dar kartą.');
            }
        }

        return $this->render('user-register', [
            'model' => $model,
        ]);
    }

    /**
     * Register action for first user.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionUserAdminRegister()
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $post = Yii::$app->request->post();
        $model = new User();
        $model->scenario = User::SCENARIO_CREATE;

        if (!empty($post)) {
            if ($model->createNewUser($post)) {
                Yii::$app->session->setFlash('success', 'Vartotojo sąskaita sėkmingai sukurta.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Vartotojo sąskaitos sukurti nepavyko. Pabandykite dar kartą.');
            }
        }

        return $this->render('user-admin-register', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionUserLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays all users.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionUserList()
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $user = new User();
        $user->scenario = User::SCENARIO_SEARCH;
        $userProvider = $user->search(Yii::$app->request->get());

        return $this->render('user-list', [
            'model' => $user,
            'modelProvider' => $userProvider,
        ]);
    }

    /**
     * Renders profile viewing.
     *
     * @param integer $id User's ID.
     * @return string
     * @throws HttpException
     */
    public function actionUserView($id = null)
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (empty($id)) {
            throw new ForbiddenHttpException('Trūksta parametrų.');
        }

        if ($id == 1 && Yii::$app->user->id != $id) {
            throw new ForbiddenHttpException('Pagrindinio administratoriaus sąskaita negali būti peržiūrėta arba koreguota.');
        }

        $model = (new User())->findOne(['id' => $id]);

        if (is_null($model)) {
            throw new NotFoundHttpException('Vartotojas nerastas.');
        }

        return $this->render('user-view', [
            'model' => $model,
        ]);
    }

    /**
     * Changes information about User.
     *
     * @param integer $id User ID.
     * @return string json_encode Results.
     * @throws HttpException User not found.
     */
    public function actionChangeUser($id = null)
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $post = Yii::$app->request->post();

        if (empty($post)) {
            throw new ForbiddenHttpException('Tiesioginis priėjimas draudžiamas.');
        }

        $attribute = key($post['User']);

        if (!in_array($attribute, ['username', 'real_name', 'password', 'email', 'type'])) {
            return json_encode(['output' => '', 'message' => 'Redaguojamas atributas nepriimamas.']);
        } elseif (Yii::$app->user->identity->type < 3) {
            return json_encode(['output' => '', 'message' => 'Tik administratorius gali vykdyti šiuos veiksmus.']);
        } elseif ($id == 1) {
            return json_encode(['output' => '', 'message' => 'Pagr. administratoriaus duomenų keisti negalima.']);
        }

        $model = (new User())->findOne($id);

        if (is_null($model)) {
            return json_encode(['output' => '', 'message' => 'Vartotojas nerastas.']);
        }

        $model->scenario = User::SCENARIO_EDIT;
        $model->$attribute = $post['User'][$attribute];

        if ($attribute == 'type') {
            if (!in_array($post['User']['type'], [1, 2, 3])) {
                return json_encode(['output' => '', 'message' => 'Netinkamas tipas.']);
            }

            $post['User'][$attribute] = User::getTypeName()[$post['User']['type']];
        }

        if ($model->save())
            return json_encode(['output' => Html::encode($post['User'][$attribute]), 'message' => '']);
        else
            return json_encode(['output' => '', 'message' => $model->firstErrors[$attribute]]);
    }

    /**
     * Removes existing user.
     *
     * @param integer $id User's ID.
     * @return string
     * @throws HttpException
     */
    public function actionUserRemove($id = null)
    {
        if (Yii::$app->user->identity->type < 3) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (empty($id)) {
            throw new ForbiddenHttpException('Trūksta parametrų.');
        }

        if ($id == 1) {

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

if (Yii::$app->errorHandler->exception->statusCode == 403) {
    $this->title = 'Leidimas neduotas';
} elseif (Yii::$app->errorHandler->exception->statusCode == 404) {
    $this->title = $message = 'Puslapis nerastas';
} else {
    $this->title = $message = 'Serverio klaida';
}
?>

<div class="site-error">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>Vykdant Jūsų užklausą, įvyko klaida. Pabandykite grįžti atgal ir pakartoti.</p>

    <button class="btn btn-info" onclick="window.history.back()">Grįžti atgal</button><br><br><br>

    <?php if (Yii::$app->errorHandler->exception->statusCode == 403): ?>
        <img src="../web/images/403-Page-Forbidden.png" style="width: 45%">
    <?php elseif (Yii::$app->errorHandler->exception->statusCode == 404): ?>
        <img src="../web/images/404-Page-Not-Found.png">
    <?php else: ?>
        <img src="../web/images/500-Internal-Error.png" style="width: 17%">
    <?php endif; ?>
</div>

views/site/index.php
<?php

use miloschuman\highcharts\Highcharts;
use yii\web\View;

/** @var View $this */
/** @var array $list Months as string. */
/** @var array $ordersAmount The amount of orders for each month as string. */
/** @var array $specificUserApproved The amount of orders approved for current user. */

$this->title = 'Pagr. Puslapis';
?>

<div class="site-index">
    <div class="jumbotron">
        <h1>Sveiki atvykę, <?php echo Yii::$app->user->identity->username ?>!</h1><br>

        <?php
        echo Highcharts::widget([
            'options' => '{
                "title": { "text": "Užsakymų kiekis per paskutinių 12 mėnesių" },
                "subtitle": { "text": "Bendras užsakymų kiekis ir kiek Jūs patvirtinote jų kiekvieną mėnesį." },
                "legend": "false",
                "xAxis": {
                    "categories": ['.$list.']
                },
                "yAxis": {
                    "title": { "text": "Užsakymų kiekis (vnt.)" }
                },
                "series": [
                    {
                        "type": "areaspline",
                        "name": "Užsakymų",
                        "data": ['.$ordersAmount.']
                    },
                    {
                        "name": "Jūs patvirtinote užsakymų",
                        "data": ['.$specificUserApproved.'],
                        "color": "green"
                    }
                ],
                "plotOptions": {
                    "area": {
                        "fillColor": {
                            "linearGradient": {
                                "x1": 0,
                                "y1": 0,
                                "x2": 0,
                                "y2": 1
                            }
                        }
                    }
                }
            }'
        ]);
        ?>
    </div>
</div>

views/site/item-view.php
<?php

use app\models\GlobalModel;
use app\models\Item;
use app\models\Section;
use app\models\User;
use kartik\editable\Editable;
use kartik\growl\Growl;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;

/* @var $this View */
/* @var $form ActiveForm */
/* @var $model Item */

$this->title = 'Prekės peržiūra';
$this->params['breadcrumbs'][] = $this->title;
?>

<h3>Prekės peržiūra: <b><?= $model->name ?></b></h3>

<div id="item_preview">
<?php
$owner = User::getUserName($model->owner, true);

echo DetailView::widget([
    'model' => $model,
    'attributes' => [
        [
            'attribute' => 'id',
            'format' => 'raw',
        ],
        (Yii::$app->user->identity->attributes['type'] > 1 ?
        [
            'attribute' => 'name',
            'format' => 'raw',
            'value' => Editable::widget([
                'model' => $model,
                'name' => 'Item[name]',
                'asPopover' => true,
                'value' => Html::encode($model->name),
                'preHeader' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> ',
                'header' => 'Redaguoti pavadinimą',
                'formOptions' => [
                    'action' => Url::to(['site/change-item', 'id' => $model->id])
                ],
                'editableButtonOptions' => ['class' => 'btn btn-xs btn-default'],
                'submitButton' => [
                    'class' => 'btn btn-xs btn-primary',
                    'icon' => '<i class="glyphicon glyphicon-ok"></i>',
                    'label' => '',
                ],
                'resetButton' => [
                    'class' => 'btn btn-xs btn-default',
                    'icon' => '<i class="glyphicon glyphicon-repeat"></i>',
                    'label' => '',
                ],
                'valueIfNull' => '<i>Nenustatyta</i>',
                'format' => Editable::FORMAT_BUTTON,
                'pluginEvents' => [
                    'editableSuccess' => "function(event, val, form, data) {
                        " . GlobalModel::generateGrowl() . "
                    }"
                ],
            ]),
        ] :
        [
            'attribute' => 'name',
            'format' => 'raw',
        ]),
        (Yii::$app->user->identity->attributes['type'] > 1 ?
        [
            'attribute' => 'section_id',
            'format' => 'raw',
            'value' => Editable::widget([
                'model' => $model,
                'name' => 'Item[section_id]',
                'asPopover' => true,
                'inputType' => Editable::INPUT_DROPDOWN_LIST,
                'data' => $sections,
                'value' => Html::encode(Section::retrieveSectionName($model->section_id)),
                'preHeader' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> ',
                'header' => 'Pakeisti skyrių',
                'formOptions' => [
                    'action' => Url::to(['site/change-item', 'id' => $model->id])
                ],
                'editableButtonOptions' => ['class' => 'btn btn-xs btn-default'],
                'submitButton' => [
                    'class' => 'btn btn-xs btn-primary',
                    'icon' => '<i class="glyphicon glyphicon-ok"></i>',
                    'label' => '',
                ],
                'resetButton' => [
                    'class' => 'btn btn-xs btn-default',
                    'icon' => '<i class="glyphicon glyphicon-repeat"></i>',
                    'label' => '',
                ],
                'valueIfNull' => '<i>Nenustatyta</i>',
                'format' => Editable::FORMAT_BUTTON,
                'pluginEvents' => [
                    'editableSuccess' => "function(event, val, form, data) {
                        " . GlobalModel::generateGrowl() . "
                    }"
                ],
            ]),
        ] :
        [
            'attribute' => 'section_id',
            'format' => 'raw',
            'value' => Html::encode(Section::retrieveSectionName($model->section_id)),
        ]),
        (Yii::$app->user->identity->attributes['type'] > 1 ?
        [
            'attribute' => 'amount',
            'format' => 'raw',
            'value' => Editable::widget([
                'model' => $model,
                'name' => 'Item[amount]',
                'asPopover' => true,
                'value' => Html::encode($model->amount),
                'preHeader' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> ',
                'header' => 'Redaguoti kiekį',
                'formOptions' => [
                    'action' => Url::to(['site/change-item', 'id' => $model->id])
                ],
                'editableButtonOptions' => ['class' => 'btn btn-xs btn-default'],
                'submitButton' => [
                    'class' => 'btn btn-xs btn-primary',
                    'icon' => '<i class="glyphicon glyphicon-ok"></i>',
                    'label' => '',
                ],
                'resetButton' => [
                    'class' => 'btn btn-xs btn-default',
                    'icon' => '<i class="glyphicon glyphicon-repeat"></i>',
                    'label' => '',
                ],
                'valueIfNull' => '<i>Nenustatyta</i>',
                'format' => Editable::FORMAT_BUTTON,
                'pluginEvents' => [
                    'editableSuccess' => "function(event, val, form, data) {
                        " . GlobalModel::generateGrowl() . "
                    }"
                ],
            ]),
        ] :
        [
            'attribute' => 'amount',
            'format' => 'raw',
        ]),
        [
            'attribute' => 'owner',
            'format' => 'raw',
            'value' => Html::a(Html::encode($owner['username']), ['site/user-view', 'id' => $owner['id']]),
        ],
        [
            'attribute' => 'created_at',
            'format' => 'raw',
            'value' => Html::encode(date('Y-m-d h:m:s', $model->created_at)),
        ],
    ],
]);

echo Html::a(Html::button('Grįžti į prekių sąrašą', ['class' => 'btn btn-info']), Url::to(['site/item-list'])).' ';

if (Yii::$app->user->identity->attributes['type'] > 1)
    echo Html::a(Html::button('Pašalinti šią prekę', ['class' => 'btn btn-danger']), Url::to(['site/item-remove', 'id' => $model->id]));
?>
</div>

views/site/log-view.php
<?php

use app\models\GlobalModel;
use app\models\Item;
use app\models\User;
use yii\bootstrap\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\web\View;

/* @var $this View */
/* @var $form ActiveForm */
/* @var $model Item */

$this->title = 'Veiksmų istorija';
$this->params['breadcrumbs'][] = $this->title;
?>

<div id="log_list">

<?php
echo GridView::widget([
    'layout' => '{summary}{items}{pager}',
    'summary' => 'Šiuo metu rodomas <b>{page}</b>-as puslapis (<b>{begin}</b> - <b>{end}</b> įrašai)',
    'dataProvider' => $modelProvider,
    'filterModel' => $model,
    'columns' => [
        [
            'attribute' => 'id',
            'format' => 'raw',
            'filter' => Html::input('input', 'LogModel[id]', (!empty(Yii::$app->request->get()['LogModel']['id'])) ? Yii::$app->request->get()['LogModel']['id'] : null, ['class' => 'form-control', 'placeholder' => 'ID paieška']),
        ],
        [
            'attribute' => 'user_id',
            'format' => 'raw',
            'filter' => Html::input('input', 'LogModel[user_id]', (!empty(Yii::$app->request->get()['LogModel']['user_id'])) ? Yii::$app->request->get()['LogModel']['user_id'] : null, ['class' => 'form-control', 'placeholder' => 'Vartotojo paieška']),
            'value' => function($model) {
                return User::getUserName($model->attributes['user_id']);
            }
        ],
        [
            'attribute' => 'type',
            'format' => 'raw',
            'filter' => Html::activeDropDownList($model, 'type', GlobalModel::getTypeName(), ['class' => 'form-control', 'prompt' => 'Visi tipai']),
            'value' => function($model) {
                return GlobalModel::getTypeName($model->type);
            }
        ],
        [
            'attribute' => 'content',
            'format' => 'raw',
            'filter' => Html::input('input', 'LogModel[content]', (!empty(Yii::$app->request->get()['LogModel']['content'])) ? Yii::$app->request->get()['LogModel']['content'] : null, ['class' => 'form-control', 'placeholder' => 'Turinio paieška']),
        ],
        [
            'attribute' => 'date',
            'format' => 'raw',
            'filter' => Html::input('input', 'LogModel[date]', (!empty(Yii::$app->request->get()['LogModel']['date'])) ? Yii::$app->request->get()['LogModel']['date'] : null, ['class' => 'form-control', 'placeholder' => 'Data']),
            'value' => function($model) {
                return date('Y-m-d', $model->attributes['date']);
            }
        ],
    ],
]);
?>

</div>

views/site/user-login.php
<?php

/** @var View $this */
/** @var ActiveForm $form */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\web\View;

$this->title = 'Prisijungimas';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <div id="login_form">
        <p>Šis tinklapis nėra viešam naudojimui. Prašome prisijungti, įvesdami savo vartotojo vardą ir slaptažodį:</p>

        <?php
        $form = ActiveForm::begin([
            'id' => 'login-form',
            'options' => ['class' => 'form-horizontal'],
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-12\">{input}</div>\n<div class=\"col-lg-12\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-12 control-label'],
            ],
        ]);
        ?>

        <?= $form->field($model, 'username')->textInput() ?>
        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Prisijungti', ['class' => 'btn btn-info', 'name' => 'login-button']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
    <img src="images/login.png" id="login_image">
</div>

views/site/user-view.php
<?php

use app\models\GlobalModel;
use app\models\User;
use kartik\editable\Editable;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\DetailView;

$this->title = 'Vartotojo peržiūra';
$this->params['breadcrumbs'][] = $this->title;

/** @var View $this */
/** @var User $model */
?>

<h2>Vartotojo <b><?= $model->username ?></b> peržiūra</h2>

<div id="user_preview">
<?php
echo DetailView::widget([
    'model' => $model,
    'attributes' => [
        [
            'attribute' => 'id',
            'format' => 'raw',
        ],
        [
            'attribute' => 'username',
            'format' => 'raw',
            'value' => Editable::widget([
                'model' => $model,
                'name' => 'User[username]',
                'asPopover' => true,
                'value' => Html::encode($model->username),
                'preHeader' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> ',
                'header' => 'Redaguoti prisijungimo vardą',
                'formOptions' => [
                    'action' => Url::to(['site/change-user', 'id' => $model->id])
                ],
                'submitButton' => [
                    'class' => 'btn btn-xs btn-info',
                    'icon' => '<i class="glyphicon glyphicon-ok"></i> Patvirtinti',
                ],
                'resetButton' => [
                    'class' => 'btn btn-xs btn-default',
                    'icon' => '<i class="glyphicon glyphicon-repeat"></i> Atstatyti',
                ],
                'valueIfNull' => '<i>Nenustatyta</i>',
                'pluginEvents' => [
                    'editableSuccess' => "function() {
                        ".GlobalModel::generateGrowl()."
                    }"
                ],
            ]),
        ],
        [
            'attribute' => 'real_name',
            'format' => 'raw',
            'value' => Editable::widget([
                'model' => $model,
                'name' => 'User[real_name]',
                'asPopover' => true,
                'value' => Html::encode($model->real_name),
                'preHeader' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> ',
                'header' => 'Redaguoti prisijungimo vardą',
                'formOptions' => [
                    'action' => Url::to(['site/change-user', 'id' => $model->id])
                ],
                'submitButton' => [
                    'class' => 'btn btn-xs btn-info',
                    'icon' => '<i class="glyphicon glyphicon-ok"></i> Patvirtinti',
                ],
                'resetButton' => [
                    'class' => 'btn btn-xs btn-default',
                    'icon' => '<i class="glyphicon glyphicon-repeat"></i> Atstatyti',
                ],
                'valueIfNull' => '<i>Nenustatyta</i>',
                'pluginEvents' => [
                    'editableSuccess' => "function() {
                        ".GlobalModel::generateGrowl()."
                    }"
                ],
            ]),
        ],
        [
            'attribute' => 'email',
            'format' => 'raw',
            'value' => Editable::widget([
                'model' => $model,
                'name' => 'User[email]',
                'asPopover' => true,
                'value' => Html::encode($model->email),
                'preHeader' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> ',
                'header' => 'Redaguoti el. paštą',
                'formOptions' => [
                    'action' => Url::to(['site/change-user', 'id' => $model->id])
                ],
                'submitButton' => [
                    'class' => 'btn btn-xs btn-info',
                    'icon' => '<i class="glyphicon glyphicon-ok"></i> Patvirtinti',
                ],
                'resetButton' => [
                    'class' => 'btn btn-xs btn-default',
                    'icon' => '<i class="glyphicon glyphicon-repeat"></i> Atstatyti',
                ],
                'valueIfNull' => '<i>Nenustatyta</i>',
                'pluginEvents' => [
                    'editableSuccess' => "function() {
                        ".GlobalModel::generateGrowl()."
                    }"
                ],
            ]),
        ],
        [
            'attribute' => 'type',
            'format' => 'raw',
            'value' => Editable::widget([
                'model' => $model,
                'name' => 'User[type]',
                'asPopover' => true,
                'value' => Html::encode($model->type),
                'displayValue' => Html::encode(User::getTypeName()[$model->type]),
                'preHeader' => '<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> ',
                'header' => 'Redaguoti tipą',
                'formOptions' => [
                    'action' => Url::to(['site/change-user', 'id' => $model->id])
                ],
                'submitButton' => [
                    'class' => 'btn btn-xs btn-info',
                    'icon' => '<i class="glyphicon glyphicon-ok"></i> Patvirtinti',
                    'label' => '',
                ],
                'resetButton' => [
                    'class' => 'btn btn-xs btn-default',
                    'icon' => '<i class="glyphicon glyphicon-repeat"></i> Atstatyti',
                    'label' => '',
                ],
                'valueIfNull' => '<i>Nenustatyta</i>',
                'inputType' => Editable::INPUT_DROPDOWN_LIST,
                'data' => User::getTypeName(),
                'pluginEvents' => [
                    'editableSuccess' => "function() {
                        ".GlobalModel::generateGrowl()."
                    }"
                ],
            ]),
        ],
    ]
]);

echo Html::a(Html::button('Grįžti į vartotojų sąrašą', ['class' => 'btn btn-info']), Url::to(['user-list']));
echo ' ';
echo Html::a(Html::button('Pašalinti šį vartotoją', ['class' => 'btn btn-danger']), Url::to(['user-remove', 'id' => $model->id]));
?>
</div>