models/Meal.php
<?php

namespace app\models;

use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\web\NotFoundHttpException;

/**
 * This is the model class for table "dish".
 *
 * @property integer $id
 * @property integer $category
 * @property string $name
 * @property string $description
 * @property string $image
 * @property string $price
 * @property integer $is_available
 * @property Category $category0
 * @property DishOrder[] $dishOrders
 */
class Meal extends ActiveRecord
{
    /** @const string SCENARIO_SEARCH Scenario for searching. */
    const SCENARIO_SEARCH = 'Scenario_search';

    /** @const string SCENARIO_NEW Scenario for creating new dish. */
    const SCENARIO_NEW = 'Scenario_new';

    /** @const string SCENARIO_EDIT Scenario for editing information. */
    const SCENARIO_EDIT = 'Scenario_edit';

    /** @const integer MAX_FILE_SIZE Maximum file size (10MB). */
    const MAX_FILE_SIZE = 10485760;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dish';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required', 'message' => '{attribute} negali būti tuščias.'],
            [['name'], 'string', 'length' => [3, 20],
                'tooShort' => '{attribute} yra per trumpas. Turi būti bent jau 3 simboliai.',
                'tooLong' => '{attribute} yra per ilgas. Daugiausiai 20 simbolių.',
            ],

            [['description'], 'required', 'message' => '{attribute} negali būti tuščias.'],
            [['description'], 'string', 'length' => [10, 255],
                'tooShort' => '{attribute} yra per trumpas. Turi būti bent jau 10 simbolių.',
                'tooLong' => '{attribute} yra per ilgas. Daugiausiai 255 simboliai.',
            ],

            [['image'], 'file', 'extensions' => ['png', 'jpg', 'jpeg', 'gif', 'bmp'],
                'wrongExtension' => 'Netinkamas failo formatas. Priimamos galūnės: {extensions}'
            ],
            [['image'], 'file', 'maxSize' => self::MAX_FILE_SIZE,
                'tooBig' => 'Maksimalus leidžiamas dydis: '.(self::MAX_FILE_SIZE / 1048576).' MB',
            ],
            [['image'], 'unique'],

            [['category'], 'required', 'message' => '{attribute} negali būti tuščia.'],
            [['category'], 'integer', 'message' => '{attribute} gali turėti tik skaičius.'],
            [['category'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category' => 'id']],

            [['price'], 'required', 'message' => '{attribute} negali būti tuščia.'],
            [['price'], 'double', 'message' => '{attribute} gali turėti tik skaičius.'],

            [['is_available'], 'required', 'message' => '„{attribute}" negali būti tuščias.'],
            [['is_available'], 'integer', 'message' => '{attribute} gali turėti tik skaičius.'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        return [
            self::SCENARIO_NEW => [
                'category',
                'name',
                'description',
                'image',
                'price',
                'is_available'
            ],
            self::SCENARIO_EDIT => [
                'category',
                'name',
                'description',
                'image',
                'price',
                'is_available'
            ],
            self::SCENARIO_SEARCH => [
                'category',
                'name',
                'description',
                'price',
                'is_available'
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category' => 'Kategorija',
            'name' => 'Pavadinimas',
            'description' => 'Aprašymas',
            'image' => 'Paveikslėlis',
            'price' => 'Kaina',
            'is_available' => 'Leidžiama užsisakyti',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getCategory0()
    {
        return $this->hasOne(Category::className(), ['id' => 'category']);
    }

    /**
     * @return ActiveQuery
     */
    public function getDishOrders()
    {
        return $this->hasMany(DishOrder::className(), ['dish_id' => 'id']);
    }

    /**
     * Loads new Meal object.
     *
     * @param integer $id Dish ID.
     * @return Meal $object Meal model.
     * @throws NotFoundHttpException
     */
    public static function loadMeal($id)
    {
        $object = self::findOne($id);

        if (is_null($object)) {
            throw new NotFoundHttpException('Patiekalas nerastas.');
        }

        return $object;
    }

    /**
     * Searching method.
     *
     * @param array $params Parameters.
     * @return ActiveDataProvider $query
     */
    public function search($params)
    {
        $query = self::find()
            ->select('dish.*, category.id AS cat_id, category.name AS cat_name, category.description AS cat_description')
            ->leftJoin('category', 'dish.category = category.id');

        $dataProvider = new ActiveDataProvider([
           'query' => $query,
        ]);

        if (!$this->load($params)) {
            return $dataProvider;
        }

        $query->andFilterWhere(['=', 'id', $this->id]);
        $query->andFilterWhere(['=', 'category', $this->category]);
        $query->andFilterWhere(['like', 'dish.name', $this->name]);
        $query->andFilterWhere(['=', 'description', $this->description]);

        if (!empty($params['Meal']['price'])) {
            $priceMin = (integer) explode(',', $params['Meal']['price'])[0];
            $priceMax = (integer) explode(',', $params['Meal']['price'])[1];
            $query->andFilterWhere(['between', 'price', $priceMin, $priceMax]);
        }

        if ($this->is_available == 1) {
            $query->andFilterWhere(['=', 'is_available', $this->is_available]);
        }

        return $dataProvider;
    }
}

controllers/MealController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\DishOrder;
use app\models\Meal;
use Yii;
use yii\base\InvalidCallException;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

/**
 * MealController controller class.
 *
 * @author Antanas Šiaulys <antanas.siaulys@ktu.edu>
 * @package app\controllers
 */
class MealController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'meal-index', 'meal-view', 'meal-add', 'meal-change-status', 'meal-remove', 'meal-validation',
                            'order-index', 'order-approve', 'order-decline',
                            'menu-index', 'menu-add', 'menu-view', 'menu-remove', 'menu-validation',
                            'error',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['error'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Renders and displays meals list.
     *
     * @return string
     */
    public function actionMealIndex()
    {
        $model = new Meal();
        $model->scenario = Meal::SCENARIO_SEARCH;
        $rootCategories = ArrayHelper::map(Category::getRootCategories(), 'id', 'name');

        $priceMin = 0;
        $priceMax = 0;

        $completeList = $model->search([])->getModels();
        foreach ($completeList as $row) {
            if ($row->price < $priceMin || $priceMin == 0) {
                $priceMin = round($row->price) - 1;
            } elseif ($row->price > $priceMax || $priceMax == 0) {
                $priceMax = round($row->price) + 1;
            }
        }

        return $this->render('meal-index', [
            'dataProvider' => $model->search(Yii::$app->request->get()),
            'model' => $model,
            'categoriesList' => $rootCategories,
            'priceMin' => $priceMin,
            'priceMax' => $priceMax,
        ]);
    }

    /**
     * Renders and updates meal information.
     *
     * @param null|integer $id Patiekalo ID.
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionMealView($id = null)
    {
        if (Yii::$app->user->identity->type < 2) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (is_null($id)) {
            throw new InvalidParamException('Trūksta parametrų.');
        }

        $post = Yii::$app->request->post();
        $model = Meal::loadMeal($id);

        if (empty($post)) {
            return $this->render('meal-add', [
                'model' => $model,
            ]);
        }

        $model->scenario = Meal::SCENARIO_EDIT;
        $image = $model->image;
        $model->load($post);
        $model->image = (!empty($post['removeOldImage']) ? '' : $image);

        if ($model->save()) {
            Yii::$app->session->setFlash('success', 'Patiekalo duomenys sėkmingai atnaujinti.');
        } else {
            Yii::$app->session->setFlash('error', 'Patiekalo duomenų nepavyko atnaujinti. Galimai įvesti klaidingi duomenys.');
        }

        return $this->redirect(['meal/meal-index']);
    }

    /**
     * Renders and/or adds new Meal.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionMealAdd()
    {
        if (Yii::$app->user->identity->type < 2) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $post = Yii::$app->request->post();
        $model = new Meal();
        $model->scenario = Meal::SCENARIO_NEW;

        if (empty($post)) {
            return $this->render('meal-add', [
                'model' => $model,
            ]);
        }

        $folder = Yii::$app->basePath.'/uploads';

        if (!file_exists($folder)) {
            mkdir($folder);
        }

        $model->load($post);

        if ($model->validate()) {
            $model->image = UploadedFile::getInstance($model, 'image');

            if (!is_null($model->image)) {
                if (!is_null(Meal::findOne(['image' => $model->image->baseName . '.' . $model->image->extension]))) {
                    Yii::$app->session->setFlash('error', 'Toks failas jau egzistuoja. Parinkite failui naują pavadinimą.');

                    return $this->redirect(['meal/meal-add']);
                }

                $model->image->saveAs($folder.'/'.$model->image->baseName.'.'.$model->image->extension);
                $model->image = $model->image->baseName . '.' . $model->image->extension;
            }

            if ($model->save(false)) {
                Yii::$app->session->setFlash('success', 'Naujas patiekalas sėkmingai įkeltas.');
            } else {
                Yii::$app->session->setFlash('error', 'Naujo patiekalo įkelti nepavyko. Pabandykite dar kartą.');
            }
        } else {
            Yii::$app->session->setFlash('error', 'Validacija nesėkminga (buvo įvesta klaidingų duomenų).');
        }

        return $this->redirect(['meal/meal-index']);
    }

    /**
     * Changes status to opposite.
     *
     * @param null|integer $id Meal ID.
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionMealChangeStatus($id = null)
    {
        if (Yii::$app->user->identity->type < 2) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (is_null($id)) {
            throw new InvalidParamException('Trūksta parametrų.');
        }

        $model = Meal::loadMeal($id);
        $model->scenario = Meal::SCENARIO_EDIT;
        $model->is_available = ($model->is_available ? 0 : 1);

        if ($model->save()) {
            Yii::$app->session->setFlash('success', 'Patiekalo būsena sėkmingai pakeista.');
        } else {
            Yii::$app->session->setFlash('error', 'Patiekalo būsenos pakeisti nepavyko. Pabandykite dar kartą.');
        }

        return $this->redirect(['meal/meal-index']);
    }

    /**
     * Removes existing meal.
     *
     * @param null|integer $id Meal ID.
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionMealRemove($id = null)
    {
        if (Yii::$app->user->identity->type < 2) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (is_null($id)) {
            throw new InvalidParamException('Trūksta parametrų.');
        }

        $model = Meal::loadMeal($id);

        if ($model->delete()) {
            Yii::$app->session->setFlash('success', 'Patiekalas sėkmingai ištrintas.');
        } else {
            Yii::$app->session->setFlash('error', 'Patiekalo ištrinti nepavyko. Pabandykite dar kartą.');
        }

        return $this->redirect(['meal/meal-index']);
    }

    /**
     * Validates Meal form.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionMealValidation()
    {
        if (Yii::$app->user->identity->type < 2) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (!Yii::$app->request->isPost) {
            throw new InvalidCallException('Tiesioginis priėjimas uždraustas.');
        }

        $model = new Meal();
        $model->scenario = Meal::SCENARIO_NEW;
        $model->load(Yii::$app->request->post());

        return json_encode(ActiveForm::validate($model));
    }

    /**
     * Renders View file for orders list.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionOrderIndex()
    {
        if (Yii::$app->user->identity->type < 2) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        $model = new DishOrder();
        $model->scenario = DishOrder::SCENARIO_SEARCH;

        return $this->render('order-index', [
            'dataProvider' => $model->search(Yii::$app->request->get()),
            'model' => $model,
        ]);
    }

    /**
     * Marks Order as approved.
     *
     * @param null|integer $id Order ID.
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionOrderApprove($id = null)
    {
        if (Yii::$app->user->identity->type < 2) {
            throw new ForbiddenHttpException('Leidimas neduotas.');
        }

        if (is_null($id)) {
            throw new InvalidParamException('Trūksta parametrų.');
        }

        $model = DishOrder::loadOrder($id);

        if ($model->status != 1) {
            throw new InvalidParamException('Pakeisti būsenos negalima.');
        }

        $model->scenario = DishOrder::SCENARIO_EDIT;
        $model->approver_id = Yii::$app->user->identity->id;
        $model->status = 2;

        if ($model->save()) {
            Yii::$app->session->setFlash('success', 'Užsakymas patvirtintas.');
        } else {
            Yii::$app->session->setFlash('error', 'Užsakymas patvirtinti nepavyko. Pabandykite dar kartą.');
        }

        return $this->redirect(['meal/order-index']);
    }

    /**
     * Marks Order as approved.
     *
     * @param null|integer $id Order ID.
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionOrderDecline($id = null)
    {
        if (Yii::$app->user->identity->type < 2) {

views/meal/_meal-info.php
<?php

use app\models\Category;
use app\models\DishOrder;
use app\models\Meal;
use yii\bootstrap\Html;

/** @var Meal $model */
?>

<div class="meal_info_detailed">
    <?php echo Html::img('../uploads/'.$model->image, ['style' => 'max-width: 100%']); ?>
</div>

<div class="meal_info_detailed">
    <h2><?php echo $model->name ?></h2>
    <?php echo Html::tag('p', '<i>'.$model->description.'</i>', ['style' => 'margin: 1em 0']); ?>
    <?php echo '<br>Kategorija: <b>'.Category::getCategoryChain($model->id).'</b><br>'; ?>
    <?php echo ($model->is_available ? 'Užsisakyti šį patiekalą <font color="green">galima</font>.' :
        'Užsisakyti šio patiekalo <font color="red">negalima</font>.');
    ?>
    <?php echo '<br>Kaina už vieną porciją/vienetą: <b>'.$model->price.'€</b>'; ?>
    <?php echo '<br>Užsakymų kiekis, kuriuose buvo pasirinktas šis patiekalas: <b>'.DishOrder::getAmountFromMealID($model->id).'</b> vnt.'; ?>
</div>

views/meal/_menu-info.php
<?php

use app\models\Category;
use app\models\Meal;

/** @var Category $model */
?>

<div class="menu_info_detailed">
    <h2><?php echo $model->name ?></h2>

    <?php
    if ($model->parent_id == 0) {
        if (count(Category::findAll(['parent_id' => $model->id])) == 0) {
            echo '<i>Ši šakninė kategorija neturi priskirtų subkategorijų.</i>';
        } else {
            echo '<h4>Priskirtos subkategorijos:</h4>';
        }
    } else {
        if (count(Meal::findAll(['category' => $model->id])) == 0) {
            echo '<i>Ši subkategorija neturi priskirtų patiekalų.</i>';
        } else {
            echo '<h4>Priskirti patiekalai:</h4>';
        }
    }
    ?>

    <ul>
        <?php
        if ($model->parent_id == 0) {
            $subcats = Category::findAll(['parent_id' => $model->id]);

            foreach ($subcats as $subcat) {
                echo '<li>'.$subcat['name'].'</li>';
            }
        } else {
            $meals = Meal::findAll(['category' => $model->id]);

            foreach ($meals as $meal) {
                echo '<li>'.$meal['name'].'</li>';
            }
        }
        ?>
    </ul>

    <h2>Aprašymas</h2>
    <?php echo $model->description ?>
</div>

views/meal/cart-index.php
<?php

use yii\web\ForbiddenHttpException;
use yii\web\View;

/** @var View $this */

throw new ForbiddenHttpException('Ši funkcija šiuo metu nėra sukurta.');

$this->title = 'Krepšelis';
$this->params['breadcrumbs'][] = $this->title;

views/meal/meal-add.php
<?php

use app\models\Category;
use kartik\select2\Select2;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

/** @var View $this */
/** @var ActiveForm $form */

$this->title = 'Naujo patiekalo pridėjimas';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="meal_div">
    <div id="meal_form">
        <?php
        $form = ActiveForm::begin([
            'options' => ['class' => 'form-horizontal', ['enctype' => 'multipart/form-data']],
            'enableAjaxValidation' => true,
            'validationUrl' => Url::to(['meal/meal-validation']),
        ]);

        echo $form->field($model, 'name', ['options' => ['class' => 'col-lg-6']])->textInput();

        echo $form->field($model, 'category', ['options' => ['class' => 'col-lg-6']])->widget(Select2::className(), [
            'data' => Category::getCategoryListAsDropdown(),
        ]);

        echo $form->field($model, 'description', ['options' => ['class' => 'col-lg-12']])->textarea(['rows' => 3]);

        echo $form->field($model, 'image', ['options' => ['class' => 'col-lg-12']])->fileInput([
            'accept' => 'image/*',
        ])->hint((!is_null($model->id) ? 'Jei nepasirinktas naujas failas, bus paliktas senasis.' : ''));

        if (!is_null($model->id)) {
            echo Html::beginTag('div', ['class' => 'col-lg-12']);
                echo Html::checkbox('removeOldImage', false, ['label' => 'Pašalinti senąjį failą']);
            echo Html::endTag('div');
        };

        echo $form->field($model, 'price', ['options' => ['class' => 'col-lg-6']]);

        echo $form->field($model, 'is_available', ['options' => ['class' => 'col-lg-6']])->dropDownList(
            ['Neleidžiama', 'Leidžiama'], ['value' => (!is_null($model->id) ? $model->is_available : 1)]
        );
        ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?php
                if (!is_null($model->id)) {
                    echo Html::submitButton('Atnaujinti patiekalo duomenis', ['class' => 'btn btn-info']);
                } else {
                    echo Html::submitButton('Pridėti naują patiekalą', ['class' => 'btn btn-info']);
                }
                ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/meal/meal-index.php
<?php

use app\models\Category;
use app\models\Meal;
use kartik\grid\ExpandRowColumn;
use kartik\grid\GridView;
use kartik\icons\Icon;
use kartik\select2\Select2;
use kartik\slider\Slider;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

/** @var View $this */
/** @var Meal $model */
/** @var ActiveDataProvider $dataProvider */
/** @var array $categoriesList */
/** @var integer $priceMin */
/** @var integer $priceMax */

$this->title = 'Patiekalai';
$this->params['breadcrumbs'][] = $this->title;

if (empty(Yii::$app->request->get('Meal'))) {
    $dish = [];
} else {
    $dish = Yii::$app->request->get('Meal');
}

if (array_key_exists('price', $dish)) {
    $priceCurrentMin = explode(',', $dish['price'])[0];
    $priceCurrentMax = explode(',', $dish['price'])[1];
} else {
    $priceCurrentMin = 0;
    $priceCurrentMax = 50;
}

//Pjax::begin(['enablePushState' => true, 'enableReplaceState' => false, 'timeout' => 10000]);
echo GridView::widget([
    'filterModel' => $model,
    'tableOptions' => [
        'class' => 'linked-row',
    ],
    'resizableColumns' => false,
    'caption' => '<div class="table-heading">Patiekalai</div><div class="header-buttons-right"></div>',
    'layout' => '{items}<div class="footer"><div class="footer-pagination">{pager}</div>{summary}</div>',
    'dataProvider' => $dataProvider,
    'summary' => false,
    'filterRowOptions' => [
        'style' => 'text-align: center;'
    ],
    'columns' => [
        [
            'attribute' => '',
            'format' => 'raw',
            'class' => ExpandRowColumn::className(),
            'value' => function() {
                return GridView::ROW_COLLAPSED;
            },
            'detail' => function($model) {
                return Yii::$app->controller->renderPartial('_meal-info', ['model' => $model]);
            },
            'expandIcon' => Icon::show('info-circle'),
            'collapseIcon' => Icon::show('level-up'),
            'expandTitle' => 'Peržiūrėti detalesnę informaciją',
            'collapseTitle' => 'Suskleisti detalesnę informaciją',
            'expandAllTitle' => 'Išskleisti matomų patiekalų detalesnę informaciją',
            'collapseAllTitle' => 'Suskleisti matomų patiekalų detalesnę informaciją',
        ],
        [
            'attribute' => 'name',
            'format' => 'raw',
            'headerOptions' => [
                'style' => 'text-align: center;',
            ],
            'contentOptions' => [
                'style' => 'text-align: center;',
            ],
            'value' => function($model) {
                return $model->name;
            }
        ],
        [
            'attribute' => 'category',
            'format' => 'raw',
            'filter' => Select2::widget([
                'name' => 'Meal[category]',
                'data' => Category::getCombinedCategories(),
                'value' => (array_key_exists('category', $dish) ? $dish['category'] : null),
                'options' => [
                    'prompt' => 'Visos kategorijos',
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ]),
            'headerOptions' => [
                'style' => 'text-align: center;',
            ],
            'contentOptions' => [
                'style' => 'text-align: center;',
            ],
            'value' => function($model) {
                return $model->category0->name;
            }
        ],
        [
            'attribute' => 'price',
            'format' => 'raw',
            'filter' => Slider::widget([
                'name' => 'Meal[price]',
                'value' => $priceCurrentMin.','.$priceCurrentMax,
                'sliderColor' => Slider::TYPE_PRIMARY,
                'pluginOptions' => [
                    'min' => $priceMin,
                    'max' => $priceMax,
                    'step' => 0.5,
                    'range' => true,
                ],
            ]),
            'headerOptions' => [
                'style' => 'text-align: center;',
            ],
            'contentOptions' => [
                'style' => 'text-align: center;',
            ],
            'value' => function($model) {
                return $model->price;
            }
        ],
        [
            'attribute' => 'is_available',
            'format' => 'raw',
            'filter' => Select2::widget([
                'name' => 'Meal[is_available]',
                'data' => [1 => 'Tik galimus užsisakyti', 0 => 'Įtraukti ir nepasiekiamus'],
                'hideSearch' => true,
                'value' => (array_key_exists('is_available', $dish) ? $dish['is_available'] : 0),
            ]),
            'headerOptions' => [
                'style' => 'text-align: center;',
            ],
            'contentOptions' => [
                'style' => 'text-align: center;',
            ],
            'value' => function($model) {
                return $model->is_available == 0 ? 'Neleidžiama' : 'Leidžiama užsisakyti';
            }
        ],
        [
            'attribute' => '',
            'format' => 'raw',
            'contentOptions' => ['class' => 'edit-col'],
            'value' => function($model) {
                return
                    Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::to(['meal-view', 'id' => $model->id]), [
                        'title' => 'Peržiūrėti/redaguoti',
                        'data-toggle' => 'tooltip',
                    ]);
            },
            'visible' => (Yii::$app->user->identity->type >= 2),
        ],
        [
            'attribute' => '',
            'format' => 'raw',
            'contentOptions' => ['class' => 'edit-col'],
            'value' => function($model) {
                return
                    Html::a('<span class="glyphicon glyphicon-random"></span>', Url::to(['meal-change-status', 'id' => $model->id]), [
                        'title' => 'Pakeisti statusą į '.($model->is_available ? 'nepasiekiamą' : 'pasiekiamą'),
                        'data-toggle' => 'tooltip',
                    ]);
            },
            'visible' => (Yii::$app->user->identity->type >= 2),
        ],
        [
            'attribute' => '',
            'format' => 'raw',
            'contentOptions' => ['class' => 'edit-col'],
            'value' => function($model) {
                return
                    Html::a('<span class="glyphicon glyphicon-remove-sign removalButton"></span>', '#', [
                        'title' => 'Ištrinti',
                        'data-toggle' => 'tooltip',
                        'data-id' => $model->id,
                    ]);
            },
            'visible' => (Yii::$app->user->identity->type >= 2),
        ]
    ],
    'export' => false,
]);
//Pjax::end();

if (Yii::$app->user->identity->type >= 2) {
    echo Html::a(Html::button('Pridėti naują patiekalą', ['class' => 'btn btn-info']), Url::to(['meal-add']));
}

$this->registerJs("
    var targetURL = '".Url::to(['meal-remove'])."';
", $this::POS_END);

views/meal/menu-add.php
<?php

use app\models\Category;
use kartik\select2\Select2;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

/** @var View $this */
/** @var ActiveForm $form */

$this->title = 'Naujos kategorijos pridėjimas';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="menu_div">
    <div id="menu_form">
        <?php
        $form = ActiveForm::begin([
            'options' => ['class' => 'form-horizontal'],
            'enableAjaxValidation' => true,
            'validationUrl' => Url::to(['meal/menu-validation']),
        ]);

        echo $form->field($model, 'name', ['options' => ['class' => 'col-lg-6']])->textInput();

        echo $form->field($model, 'parent_id', ['options' => ['class' => 'col-lg-6']])->widget(Select2::className(), [
            'data' => array_merge(['' => [0 => 'Tai yra tėvinė kategorija']], Category::getCombinedCategories()),
        ]);

        echo $form->field($model, 'description', ['options' => ['class' => 'col-lg-12']])->textarea(['rows' => 3]);
        ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?php
                if (!is_null($model->id)) {
                    echo Html::submitButton('Atnaujinti kategorijos duomenis', ['class' => 'btn btn-info']);
                } else {
                    echo Html::submitButton('Pridėti naują kategoriją', ['class' => 'btn btn-info']);
                }
                ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>